### ISSUE TITLE
Set some design goals

### ISSUE THREAD

**Issue by DanHartman** [cjoelfoster/first-repo#2]
@cjoelfoster Let's come up with a project we can collaborate on.  What would be interesting to both of us?
Here are some things I'd feel comfortable providing direction on:

- static website

- cloud hosted database

- TDD

**Comment by DanHartman** [comment]
@cjoelfoster I'm closing this issue and setting the goal as an online "snake" game.  It would be a fun way to practice some ideas and learn some new ones.

**Comment by cjoelfoster** [comment]
@DanHartman I'm testing communications...

**Comment by DanHartman** [comment]
Alright, what do you expect the test to return?

**Comment by cjoelfoster** [comment]
So, I'm confused; am I supposed to add the 'assets' folder inside the existing 'first-repo'? Or am I starting a new one?
