### ISSUE TITLE
Document the rules of snake

### ISSUE THREAD

**Issue by DanHartman** [cjoelfoster/first-repo#3]
The repo needs a document the describes the rule set we will follow.  This should give a description of how the snake moves, what it eats, how it nagivates, what occurs if it hits a wall, or itself.

This document should be in a top level directory called "assets."  It could potentially be accessed by the game player who wants to refresh so it should be written as if it is a manual.

**Comment by cjoelfoster** [comment]
@DanHartman I'm going to attempt to upload (via ssh) my first draft of the snake document.

**Comment by cjoelfoster** [comment]
@DanHartman I have the rough draft completed and committed, having trouble communicating with GitHub on SSH...I tried 'git push', but I don't think I'm connected. Would you please remind me how to establish my SSH connection?--Is this something I will have to do every time?

**Comment by DanHartman** [comment]
There isn't a separate `connection` step.  Can you copy and paste the error message you're receiving?

**Comment by cjoelfoster** [comment]
$ssh -T git@github.com
git@github.com: permission denied (public key)

**Comment by cjoelfoster** [comment]
I also tried:
ssh -T git-cjoelfoster@github.com, and
ssh -T cjoelfoster@github.com with the same result

**Comment by DanHartman** [comment]
what do you see if you run `ssh-add -l`

**Comment by cjoelfoster** [comment]
`the agent has no identities`

**Comment by DanHartman** [comment]
aha! We'll need to figure this out in the long run but this is a setup with the ssh agent.  Run the command `ssh-add ~/.ssh/id_rsa`.  It should probably ask for your keypass. Then try interfacing with github again.

**Comment by cjoelfoster** [comment]
`no such file or directory`
...interesting. My ssh key files seem to have disappeared...

**Comment by DanHartman** [comment]
is this a different machine?  are you using a different user? `whoami`

**Comment by cjoelfoster** [comment]
I looked inside the folder where we put them when we created the key and they are gone.
I think I know what happened. I was setting up for the Software Carpentry Workshop and I changed some settings for my username...I probably need to re-generate my SSH keys.

**Comment by cjoelfoster** [comment]
Can I just follow the instructions on GitHub `https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent`?

**Comment by DanHartman** [comment]
yup

**Comment by cjoelfoster** [comment]
Got it...it helps if you put your public key in GitHub rather than your private key...

$`git push`
`fatal: The current branch snake has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin snake`

**Comment by cjoelfoster** [comment]
Somehow I'm not able to push my new branch to the repository

**Comment by DanHartman** [comment]
so `git push` is a short hand.  The true syntax you should be using is `git push origin <branch name>`

**Comment by cjoelfoster** [comment]
Yeah...I just figured it out :)
Should be there now

**Comment by cjoelfoster** [comment]
@DanHartman How would one go about writing a unit test for a piece of documentation?

**Comment by DanHartman** [comment]
I see this document as the test for further functionality.
